Dim 0 As String = "You go right"
Dim 1 As String = "You go left"
Dim 2 As String = "You fell off the face of the earth"
Dim 3 As String = "You try to scream in space, but no one can hear you"
Dim 4 As String = "GAME OVER (That's it, what were you expecting?)"
Dim 5 As String = "You saw a dog try to eat a lemon. (This is the win condition, you win)"
